int _isupper(int ch);
int _isdigit(int ch);
int mul(int i, int j);
void print_numbers(void);
int _putchar(char ch);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
